### ISSUE TITLE
kang labels are missing

### ISSUE THREAD

**Issue by jlmelville** [hyhuang00/scRNA-DR2020#1]
Hi, I appreciate very much that you have shared so much data in such an easily digestible format. Thank you! For the `kang` dataset, the `kang_labels.npy` file is not present in the `data` folder. Unfortunately the [originating article](https://www.nature.com/articles/nbt.4042) is not available without a subscription so regenerating the labels is difficult. Is there any chance you still have this file?

Also:

* the `muraro` dataset is only available as `Muraro_labels.csv` and `Muraro_pca.csv` -- is this form the same as that used in the publication or was some log transformation applied before the PCA?
* the `stuart` dataset may have a typo in the filename for `setrat_bmnc_rna_70.npy`: probably `setrat` should be `seurat`?

**Comment by hyhuang00** [comment]
Thank you for your interest in our work! I have added the labels for the `kang` dataset and fix the typo in `stuart` dataset. For the `muraro` dataset, I believe the data format is in the same form used in the publication. I have uploaded the preprocessed version to the repository. Let me know if you have any further questions!

**Comment by jlmelville** [comment]
Thanks for so quickly adding that data.

To clarify about `muraro`, the data in `Muraro_pca.csv` is different from that in `muraro_log_pca.npy`. They both are of shape `(2282, 100)` but the first row of `Muraro_pca.csv` starts as `-5.964591, -2.222875,  0.258055`, while `muraro_log_pca.npy` starts `-8.61244845,  -0.14260658,  -1.17115708`. From the naming of those files, is it safe to assume that `Muraro_pca` contains the PCA-transformed raw expression data and `muraro_log_pca.npy` has PCA applied to the log-transformed data? As a result I assume you would recommend that `muraro_log_pca.npy` should be used in preference to  `Muraro_pca`?

**Comment by hyhuang00** [comment]
I would recommend you to use `muraro_log_pca.npy`.

**Comment by jlmelville** [comment]
Thanks!
